"""
Medical Report Generator for Diabetic Retinopathy Detection System
Generates professional medical-grade diagnosis reports
"""

from datetime import datetime
import os

class MedicalReportGenerator:
    """
    Generates comprehensive medical reports for DR detection results
    Follows medical documentation standards
    """
    
    # DR Severity Classification
    SEVERITY_LEVELS = {
        0: {"name": "No DR", "risk": "Low", "color": "Green"},
        1: {"name": "Mild", "risk": "Moderate", "color": "Yellow"},
        2: {"name": "Moderate", "risk": "High", "color": "Orange"},
        3: {"name": "Severe", "risk": "Very High", "color": "Red"},
        4: {"name": "Proliferative", "risk": "Critical", "color": "Dark Red"}
    }
    
    # Medical Recommendations based on severity
    RECOMMENDATIONS = {
        0: "Continue routine eye checkups annually. Maintain good blood glucose control.",
        1: "Schedule ophthalmology consultation within 3-6 months. Intensify diabetes management.",
        2: "Schedule urgent ophthalmology consultation within 1-3 months. Implement aggressive glucose control.",
        3: "Schedule immediate ophthalmology consultation. Requires specialist assessment and possible treatment.",
        4: "URGENT: Immediate referral to ophthalmology specialist required. Laser treatment may be needed."
    }
    
    def __init__(self, patient_name, patient_id, age, gender, doctor_name="Team Thiran"):
        """
        Initialize report with patient information
        
        Args:
            patient_name: Patient's full name
            patient_id: Unique patient identifier from database
            age: Patient age
            gender: Patient gender
            doctor_name: Screening physician name
        """
        self.patient_name = patient_name
        self.patient_id = patient_id
        self.age = age
        self.gender = gender
        self.doctor_name = doctor_name
        self.report_date = datetime.now()
        self.report_id = self._generate_report_id()
    
    def _generate_report_id(self):
        """Generate unique report ID"""
        timestamp = self.report_date.strftime("%Y%m%d%H%M%S")
        return f"DR-{self.patient_id}-{timestamp}"
    
    def generate_report(self, severity_level, confidence_score, image_path=None):
        """
        Generate complete medical report
        
        Args:
            severity_level: DR classification (0-4)
            confidence_score: Model confidence percentage
            image_path: Path to analyzed image
        
        Returns:
            dict: Complete report data
        """
        if severity_level not in self.SEVERITY_LEVELS:
            raise ValueError(f"Invalid severity level: {severity_level}")
        
        severity_info = self.SEVERITY_LEVELS[severity_level]
        
        report = {
            "report_id": self.report_id,
            "report_date": self.report_date.strftime("%Y-%m-%d %H:%M:%S"),
            "patient": {
                "name": self.patient_name,
                "id": self.patient_id,
                "age": self.age,
                "gender": self.gender
            },
            "screening": {
                "physician": self.doctor_name,
                "facility": "Team Thiran - DR Detection System",
                "imaging_modality": "Retinal Fundus Photography"
            },
            "findings": {
                "severity_level": severity_level,
                "classification": severity_info["name"],
                "risk_level": severity_info["risk"],
                "confidence": f"{confidence_score:.1f}%",
                "image_analyzed": os.path.basename(image_path) if image_path else "Not specified"
            },
            "clinical_assessment": self._get_clinical_assessment(severity_level),
            "recommendations": self.RECOMMENDATIONS[severity_level],
            "disclaimer": "This report is generated by AI-assisted screening and should be confirmed by a qualified ophthalmologist.",
            "next_steps": self._get_next_steps(severity_level)
        }
        
        return report
    
    def _get_clinical_assessment(self, severity_level):
        """Get clinical assessment text based on severity"""
        assessments = {
            0: "No diabetic retinopathy detected. Retinal examination appears normal.",
            1: "Mild diabetic retinopathy detected. Microaneurysms and/or mild hemorrhages present.",
            2: "Moderate diabetic retinopathy detected. More extensive microaneurysms, hemorrhages, and hard exudates.",
            3: "Severe diabetic retinopathy detected. Extensive retinal involvement with venous beading and intraretinal microvascular abnormalities.",
            4: "Proliferative diabetic retinopathy detected. Neovascularization requiring urgent intervention."
        }
        return assessments[severity_level]
    
    def _get_next_steps(self, severity_level):
        """Get next clinical steps based on severity"""
        steps = {
            0: ["Annual eye examination", "Regular diabetes screening", "Lifestyle modifications"],
            1: ["Ophthalmology consultation within 3-6 months", "Intensified glucose control", "Blood pressure management"],
            2: ["Urgent ophthalmology consultation", "Possible laser therapy assessment", "Aggressive metabolic control"],
            3: ["Immediate specialist referral", "Possible intravitreal injections", "Close monitoring"],
            4: ["EMERGENCY: Same-day ophthalmology consultation", "Possible laser treatment", "Intravitreal injections may be needed"]
        }
        return steps[severity_level]
    
    def get_report_summary(self, report):
        """
        Get SMS-compatible summary of report
        
        Args:
            report: Complete report dict
        
        Returns:
            str: Concise SMS text
        """
        patient = report["patient"]
        findings = report["findings"]
        
        summary = f"""Team Thiran DR Detection Report

Patient: {patient['name']}
Report ID: {report['report_id']}
Date: {report['report_date']}

FINDINGS:
Classification: {findings['classification']}
Risk Level: {findings['risk_level']}
Confidence: {findings['confidence']}

RECOMMENDATION:
{report['recommendations']}

Next: Consult ophthalmologist for confirmation.
Report: {report['disclaimer']}"""
        
        return summary
    
    def get_report_text(self, report):
        """
        Get formatted report text for WhatsApp message
        
        Args:
            report: Complete report dict
        
        Returns:
            str: Formatted full report text
        """
        patient = report["patient"]
        findings = report["findings"]
        screening = report["screening"]
        
        text = f"""📋 *DIABETIC RETINOPATHY SCREENING REPORT*

*Patient Information*
Name: {patient['name']}
ID: {patient['id']}
Age: {patient['age']} years
Gender: {patient['gender']}

*Report Details*
Report ID: {report['report_id']}
Date: {report['report_date']}
Facility: {screening['facility']}

*Clinical Findings*
Classification: *{findings['classification']}*
Risk Level: {findings['risk_level']}
Model Confidence: {findings['confidence']}
Image Analyzed: {findings['image_analyzed']}

*Clinical Assessment*
{report['clinical_assessment']}

*Recommendations*
{report['recommendations']}

*Next Steps*
"""
        for i, step in enumerate(report['next_steps'], 1):
            text += f"{i}. {step}\n"
        
        text += f"\n⚠️ {report['disclaimer']}\n"
        text += "\nℹ️ Please consult a qualified ophthalmologist for confirmation."
        
        return text


def create_report(username, severity_level, confidence_score, image_path=None, age=None, gender=None):
    """
    Convenience function to create report
    
    Args:
        username: Patient username from database
        severity_level: DR classification (0-4)
        confidence_score: Model confidence percentage
        image_path: Path to analyzed image
        age: Optional patient age
        gender: Optional patient gender
    
    Returns:
        dict: Complete report data
    """
    generator = MedicalReportGenerator(
        patient_name=username,
        patient_id=username,
        age=age or "N/A",
        gender=gender or "N/A"
    )
    
    report = generator.generate_report(
        severity_level=severity_level,
        confidence_score=confidence_score,
        image_path=image_path
    )
    
    return report
